### PR TITLE
Version 1.0 - (Hooks)

### PR DESCRIPTION
**Pull request by allanhortle**
## Features
- [x] hooks
- [x] no normalizing option for api
- [x] loading boundary
- [x] move mapResponseToProps to LoadingBoundaryHoc
- [x] add update and toState functions to Message
- [x] docs
- [x] Schema shorthand notation
- [x] make logger unique to provider via a prop
- [x] caching support (this could be done in 1.1)
- [ ] interactive examples
- [x] Value / Id schema
- [x] make Message polymorphic
- [x] message breaks on get undefined
- [x] request hocks break if they return while unrendered
- [x] uncaught errors in action promises
- [ ] map schema should be able to take no arguments

Should value schema even exist? Should entity schemas without a shape be a value?

# Refactors
- [x] use plain lerna without workspaces
- [x] lock package versions
- [x] remove _ from reducer state
- [x] remove all deprecated things
- [x] change resultKey => responseKey
- [x] change normalizeCount to something more inline with frameCount/responseCount
- [x] Schema: Use plain class syntax
- [x] Schema: Rename definition to shape
- [x] Schema: Flatten options on to class. (Keep the two argument syntax)
- [x] Schema: Remove immutable methods. (Let people mutate the schemas)
- [x] Schema: Kill the class hierarchy (make the flow less complicated)
- [x] Schema: Replace denormalizeFilter with a deleteEntity function (Structural Schemas still filter DELETED_ENTITY)
- [ ] 100% test coverage
-

## Docs
- [ ] Entity Schema defaults
- [ ] NullSchema
- [ ] Value/Id Schema
- [x] Api Order
- [x] Move Examples from Api to Guides
- [x] remove useAutoRequest
- [x] Guide Sections Getting Started / Common things / Weird Stuff
- [x] Guide - Basics: Getting Started
- [ ] Guide - Basics: Normalize Some Data
- [ ] Guide - Basics: Request Hooks & Messages
- [ ] Guide - Common: Data Fetching Triggers
- [ ] Guide - Common: Request States & Fallbacks
- [ ] Guide - Common: Schemas
- [ ] Guide - Common: LoadingBoundary
- [ ] Guide - Common: Connecting to an API
- [ ] Guide - Common: Custom Loading Behaviour
- [ ] Guide - Common: Service Based Api
- [ ] Guide - Advanced: Observables
- [ ] Guide - Advanced: Websockets
- [ ] Guide - Advanced: Polling
- [ ] Guide - Advanced: List Manipulation
- [ ] Guide - Advanced: Caching
- [ ] Guide - Advanced: Tainted Entities
- [ ] Guide - Advanced: Deleting Entities

---
## Breaking Changes
* (react-enty) ResultKey is internal now. Removed `RequestHoc.config.updateResultKey`
* (react-enty) Messages are now polymorphic
* (react-enty) EntityProvider has been renamed to Provider and is now a component not a hoc
* (react-enty) apiItem.request has changed to apiItem.requestHoc
* (react-enty) EntityApi accepts parameters in reverse order
* (enty): rename ValueSchema to IdSchema
* (enty): make CompositeEntitySchema extend EntitySchema
* (enty): schemas exports are now classes not functions
* (enty): rename options.definition to options.shape
* (enty): rename options.constructor to options.create
* (enty): remove schema set/update/get methods
* (enty): Logger is now a `debug` prop on providers
* (enty-state) Request Actions no longer denormalize state. Render bindings must do this now.
* (enty-state) RequestState has isState booleans instead of a type property
* (enty-state) RequestState constructors are static methods on the class
* (enty-state) Message constructors are static methods on the class
* (enty-state) Message are polymorphic and their constructors are require all fields
* (react-enty) Message.onRequest is now Message.request

### CODE REVIEW

**Comment by dxinteractive** [comment]
Just logging some more undocumented breaking changes
- `apiItem.request` has changed to `apiItem.requestHoc`
- `EntityProvider` has been renamed to `Provider`, at some point has changed from a HOC to a component

**Comment by dxinteractive** [comment]
Just logging some more undocumented breaking changes
- `apiItem.request` has changed to `apiItem.requestHoc`
- `EntityProvider` has been renamed to `Provider`, at some point has changed from a HOC to a component

**Comment by allanhortle** [comment]
I've put those in the master list.

**Comment by dxinteractive** [comment]
Best add `import` statements to your docs and examples. Looking up API docs for `message` and `requestState` doesn't say how to get `RequestState` into the project.

**Comment by dxinteractive** [comment]
Another braking change - looks like `options.constructor` is now `options.create`?

**Comment by dxinteractive** [comment]
Another breaking change - seems that `MapSchema` no longer accepts an `options.constructor` / / `options.create` or an `options.merge` option. Which is probably a good thing.

**Comment by dxinteractive** [comment]
Breaking change `MapSchema()` previously allowed for zero arguments, `new MapSchema()` now requires a shape to be passed.

**Comment by dxinteractive** [comment]
Another breaking change: EntitySchemas `idAttribute` is now called `id`

**Comment by dxinteractive** [comment]
It seems errors thrown during normalisation are being silently swallowed? Try returning some data that has no `id` in it, enty will silently catch this error internally and simply not to a `ENTY_RECEIVE`:

"Error: learningResource_learningResourceEntity.id() returned undefined. Entities need some sort of id so they can be stored and retrieved. You should check the schema to see what is going on."

**Comment by dxinteractive** [comment]
It seems that the promise returned from the `onRequest()` hooks always resolves even when an error has occurred. Is that intentional? I'd like to chain off of that returned promise, and do something only if the request succeeded. I assume the reason the empty catch block is there is so that you don't force the user to always `.catch(() => {})` every time they use a request hook?

I know you're planning on redoing this part anyway.

- One possible solution - I chain off request hook promises pretty rarely, I wouldn't mind opting-in to having the promise (or observable) returned. Maybe it normally silently catches errors unless you do that.
- Or it always resolves, and theres something in the payload that says whether the request succeeded.

```
return dispatch(requestAction(payload, {responseKey}))
                .then(() => {
                    if(mounted.current) {
                        return responseRef.current;
                    }
                })
                .catch(() => {}); // eats up the returned promises knowledge of the failure
```

**Pull request merged**
